name: The MAP1_S02 map overlay (MAP1_S02)
sha1: 05F12AD23F5F4696745659577BE3516D30E9CEEC
options:
  basename: MAP1_S02.BIN
  target_path: assets/Trial-USA/VIN/MAP1_S02.BIN
  base_path: ../../../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map1_s02
  src_path: src/maps/map1_s02
  build_path: build

  ld_script_path: linkers/maps/map1_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/Trial-USA/sym.main.txt
    - configs/Trial-USA/sym.bodyprog.txt
    - configs/Trial-USA/maps/sym.map1_s02.txt
  reloc_addrs_path:
    - configs/Trial-USA/maps/rel.map1_s02.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map1_s02.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map1_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s02
    type: code
    start: 0
    vram: 0x800C1D18
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1FE8, asm, map1_s02]
      - [0x13F04, data, map1_s02]
  - [0x1BB00]
