name: Main Game Logic Overlay (BODYPROG)
sha1: ACF0D15E688704190574A002249CE18FCDC20A35
options:
  basename: BODYPROG.BIN
  target_path: assets/Trial-USA/1ST/BODYPROG.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/bodyprog
  src_path: src/bodyprog
  asset_path: asm/bodyprog
  build_path: build/

  ld_script_path: linkers/bodyprog.ld

  find_file_boundaries: False
  gp_value: 0x8001EF30
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
   # - configs/Trial-USA/screens/sym.b_konami.txt
   # - configs/Trial-USA/screens/sym.stream.txt
   # - configs/Trial-USA/screens/sym.saveload.txt
   # - configs/Trial-USA/screens/sym.options.txt
   # - configs/Trial-USA/screens/sym.credits.txt
    - configs/Trial-USA/sym.bodyprog.txt
    - configs/Trial-USA/sym.main.txt
  reloc_addrs_path:
    - configs/Trial-USA/rel.bodyprog.txt

  undefined_funcs_auto_path: linkers/undefined_funcs_auto.bodyprog.txt
  undefined_syms_auto_path: linkers/undefined_syms_auto.bodyprog.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: bodyprog
    type: code
    start: 0x0
    vram: 0x80020ED0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x7010, asm, bodyprog]
      - [0x807F0, data, bodyprog]
  - [0xA0F00]
