name: Main Executable (SLUS_900.50)
sha1: 0B6DB67FAC38FF210BC097362F5B3A3F7E41ABD5
options:
  basename: main
  target_path: rom/Trial-USA/SLUS_900.50
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/main
  src_path: src/main
  build_path: build/

  ld_script_path: linkers/main.ld

  find_file_boundaries: False
  gp_value: 0x8001EF30
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  symbol_addrs_path:
    - configs/Trial-USA/sym.bodyprog.txt
    - configs/Trial-USA/sym.main.txt
  reloc_addrs_path:
    - configs/Trial-USA/rel.main.txt

  undefined_funcs_auto_path: linkers/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/undefined_syms_auto.main.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0xF70, asm, main]
      - [0xB640, data, main]
  - [0x10000]
