name: Video stream logic overlay (STREAM)
sha1: 57994EA4ABE00442A73C39368B2E618195B00808
options:
  basename: STREAM.BIN
  target_path: assets/JAP-2/VIN/STREAM.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/screens/stream
  src_path: src/screens/stream
  asset_path: asm/screens/stream
  build_path: build/

  ld_script_path: linkers/screens/stream.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP-2/screens/sym.stream.txt
    - configs/JAP-2/sym.bodyprog.txt
    - configs/JAP-2/sym.main.txt
  reloc_addrs_path:
    - configs/JAP-2/screens/rel.stream.txt

  undefined_funcs_auto_path: linkers/screens/undefined_funcs_auto.stream.txt
  undefined_syms_auto_path: linkers/screens/undefined_syms_auto.stream.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: stream
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1B0, asm, stream]
      - [0x1988, data, stream]
  - [0x12C00]
  